<a href="https://colab.research.google.com/github/positivezenart/positivezenart/blob/main/Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    # write your code
    num_col_a = len(A[0])
    num_rows_b = len(B)

    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
  
    if num_col_a == num_rows_b:
      for i in range (len(A)):
        for j in range (len(B[0])):
          for k in range (len(B)):
              result[i][j] += A[i][k]*B[k][j]

     # for p in result:
        #  print("Matrix multiplication is possible")
          #print(p)
      return result
         
    else:
      print("Matrix is not possible")

print("Enter order of 1st matrix:")
m,n = list(map(int,input().split()))

print("Enter Row wise values")
mat1 = []

for i in range(m) :
    print("Enter row",i,"value:")
    row = list(map(int,input().split()))
    mat1.append(row)
 
print("Enter order of 2nd matrix:")
p,q = list(map(int,input().split()))
 
print("Enter Row wise values")
mat2 = []
 
# row wise insertion in the matrix
for j in range(p) :
    print("Enter row",j,"value:")
    row = list(map(int,input().split()))
    mat2.append(row)

print("Matrix 1:",mat1)
print("Matrix 2:",mat2)
  
A=mat1
B= mat2
    
matrix_mul(A, B)

Enter order of 1st matrix:
2 3
Enter Row wise values
Enter row 0 value:
2 1 3
Enter row 1 value:
2 1 4
Enter order of 2nd matrix:
2 3
Enter Row wise values
Enter row 0 value:
2 1 5
Enter row 1 value:
3 2 6
Matrix 1: [[2, 1, 3], [2, 1, 4]]
Matrix 2: [[2, 1, 5], [3, 2, 6]]
Matrix is not possible


In [ ]:
#2nd method

def matrix_mul(A, B):

    num_col_a = len(A[0])
    num_rows_b = len(B)

    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]

    if num_col_a == num_rows_b:
      for i in range (len(A)):
        for j in range (len(B[0])):
          for k in range (len(B)):
              result[i][j] += A[i][k]*B[k][j]

      return result

    else:

      print("Matrix is not possible")

     

A = [[1, 3, 4],
     [2, 5, 7],
     [5, 9, 6]]

B = [[1, 0, 0],
     [0, 1, 0],
     [0, 0, 1]]
C = [[1, 3, 4], [5, 9, 6]]

D = [[1, 0, 0], [0, 0, 1]]
      

print(matrix_mul(A, B))
print(matrix_mul(C,D))
  


[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
Matrix is not possible
None


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
import random
from random import uniform
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]


#Step 1

#a) Sum of all elements in the list
S= sum(A)
#b) Normalizaing using the sum
normalized_sum = [ele/S for ele in A]
#c) #Calculating cumulative normalized sum
cum_nor_sum = []
cum_nor_sum.append(normalized_sum[0])
for i in range(1,len(normalized_sum),1):
    cum_nor_sum.append(cum_nor_sum[-1]+ normalized_sum[i])

def pick_a_number_from_list(cum_norm_sum):
    # your code here for picking an element from with the probability propotional to its magnitude

    #Step 2: Sample one value from cum_nor_sum
    r = random.random()
    for i in range(len(cum_nor_sum)): #Step 3: Probablity sampling
      if r < cum_nor_sum[i]: #checking if r<A[i]
              return A[i]

random_element=[]
for i in range(1, 100):
      random_element.append(pick_a_number_from_list(cum_nor_sum))
print(random_element)
       

A=sorted(A)
for ele in A:
  print("Number:{0},Frquency:{1}".format(ele,random_element.count(ele))) # checking the frequency of sampling



[79, 100, 79, 100, 100, 45, 27, 100, 45, 100, 79, 100, 100, 100, 100, 45, 10, 100, 45, 79, 100, 79, 100, 100, 45, 100, 100, 28, 79, 13, 79, 100, 13, 10, 27, 100, 100, 45, 6, 100, 100, 79, 13, 100, 79, 79, 100, 100, 45, 10, 100, 28, 28, 79, 100, 6, 5, 100, 100, 6, 45, 10, 100, 100, 45, 79, 10, 100, 28, 45, 45, 28, 79, 100, 10, 10, 79, 28, 100, 100, 45, 28, 100, 79, 100, 6, 79, 79, 100, 45, 100, 79, 79, 45, 100, 45, 79, 100, 79]
Number:0,Frquency:0
Number:5,Frquency:1
Number:6,Frquency:4
Number:10,Frquency:7
Number:13,Frquency:3
Number:27,Frquency:2
Number:28,Frquency:7
Number:45,Frquency:15
Number:79,Frquency:21
Number:100,Frquency:39


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):# Function to replace digits with
    # write your code 
   return '#' * len(re.sub(r'\D', '', String)) # modified string which is after replacing the # with digits

String = str(input("Enter a string with digits\n")) #inputing the string
print(replace_digits(String)) #printing the result

Enter a string with digits
567rtgc
###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
import math
# you can free to change all these codes/structure
def display_dash_board(students, marks):
    Marks_of_Students = list(zip(Students, Marks)) #Zipping elements to create a list of tuples
    Marks_of_Students.sort(key= lambda item: item[1]) #Sorting elements in ascending order
    print((Marks_of_Students))
    
    top_5_students = least_5_students = Marks_of_Students
    if len(Marks_of_Students)>5:
      # write code for computing top top 5 students
      top_5_students = Marks_of_Students[:-6: -1] #Slicing and reversing an element
      # write code for computing top least 5 students
      least_5_students =Marks_of_Students[:5] #displaying first 5 scores,
      # write code for computing top least 5 students
      students_within_25_and_75 = Marks_of_Students[math.ceil(0.25 *len(Marks_of_Students)):math.floor(0.75 * len(Marks_of_Students))]
    
    return top_5_students, least_5_students, students_within_25_and_75

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
print(f"Top 5 students based on highest marks\n:{top_5_students}")
print(f"least 5 students based on highest marks\n:{least_5_students}")
print(f"Students within 25th and 75th percentile\n:{students_within_25_and_75}")

[('student3', 12), ('student4', 14), ('student9', 22), ('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48), ('student2', 78), ('student10', 80), ('student8', 98)]
Top 5 students based on highest marks
:[('student8', 98), ('student10', 80), ('student2', 78), ('student5', 48), ('student7', 47)]
least 5 students based on highest marks
:[('student3', 12), ('student4', 14), ('student9', 22), ('student6', 43), ('student1', 45)]
Students within 25th and 75th percentile
:[('student6', 43), ('student1', 45), ('student7', 47), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    total_list_of_closest_points_to_p =[]
    Sorted_closest_to_p = []

    for point in S:

# Calculating denomiator and nominator to find cosine distance

      denominator = math.sqrt((point[0] ** 2) + (point[1] ** 2)) * math.sqrt((P[0] ** 2) + (P[1] ** 2))
      numerator = point[0] *P[0] + point[1] * P[1]

      
#Calculating cosine distance between two points

      if denominator != 0:
        cosine_distance = math.acos(numerator/denominator) # calculating cosine distance
        total_list_of_closest_points_to_p.append((cosine_distance,point)) # appending values

#[(2.0344439357957027, (1, 2)), (1.8545904360032246, (3, 4)), (2.9996955989856287, (-1, 1)), (0.06512516333438509, (6, -7)), (2.498091544796509, (0, 6)), (1.2021004241368467, (-5, -8)), (1.4288992721907328, (-1, -1)), (0.9272952180016123, (6, 0)), (0.14189705460416438, (1, -1))]
#print(total_list_of_closest_points_to_p)

    for item in sorted(total_list_of_closest_points_to_p,key=lambda x:x[0])[:5]: #looping through sorted items

#Sorting values based on cosine distance, But choosing data points{item[1]} instead of cosine distance[item{0}]
        Sorted_closest_to_p.append(item[1]) 

    return Sorted_closest_to_p # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P) # Calling function
print(f"5 closest points(based on cosine distance) in S from P:{points}" ) #print the returned values

5 closest points(based on cosine distance) in S from P:[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    sign_of_equation_with_red_points = -1 #Vairbale

    # Taking first red tuple, applying into ax+by+c equation to test if the evaluated value> 0

    if eval(line.replace('x', '*%s' % red[0][0]).replace('y', '*%s' % red[0][1])) > 0: 
        sign_of_equation_with_red_points = 1

    for red_point in red:

      # To checking if the both condition evaulte to be true, if it evaluated to be true, single point is on the other side of the Line Equation

        if sign_of_equation_with_red_points == -1 and eval(line.replace('x','*%s' % red_point[0]).replace('y','*%s' % red_point[1]))>0:

          return "No"
      # To checking if the both condition evaulte to be true, if it evaluated to be true, single point is on the other side of the Line Equation

        if sign_of_equation_with_red_points == 1 and eval(line.replace('x','*%s' % red_point[0]).replace('y','*%s' % red_point[1]))<0:

          return "No"

    #Now for blue points

    sign_of_equation_with_blue_points = -1 * sign_of_equation_with_red_points


    for blue_point in blue: 

      # To checking if the both condition evaulte to be true, if it evaluated to be true, single point is on the other side of the Line Equation

        if sign_of_equation_with_blue_points == -1 and eval(line.replace('x', '*%s' % blue_point[0]).replace('y', '*%s' % blue_point[1])) > 0:

          return 'NO'

      # To checking if the both condition evaulte to be true, if it evaluated to be true, single point is on the other side of the Line Equation

        if sign_of_equation_with_blue_points == 1 and eval(line.replace('x','*%s' % blue_point[0])).replace('y','*%s' % blue_point[1])<0:

          return 'NO'

    #if none of the steps returns no, ed points are one side of the line and blue points are other side of the line
      
    return 'Yes'

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

print("A line that separates oranges and apples:")

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

A line that separates oranges and apples:
Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    non_empty_list = [] # Creating an empty non empty list
    string_split = string.split(',') # split the string by ","
    print(string_split)

    for i in range(len(string_split)):
      if string_split[i] != '_':
        non_empty_list.append(i)

    non_empty_list.append(len(string_split)-1)
    print(non_empty_list)

    start_position = 0

    for element in non_empty_list: #looping through non empty elemetns

      cumulative_sum_prev_and_next_value = int(string_split[element]) if string_split[element] != '_' else 0 
      cumulative_sum_prev_and_next_value += int(string_split[start_position]) if string_split[
    start_position] != '_' and start_position != element else 0

      int_to_replace_each_previous_empty_cell = cumulative_sum_prev_and_next_value //(element -start_position+ 1) # calculating integer replacing value

      string_split = [
            int_to_replace_each_previous_empty_cell if start_position <= x <= element else string_split[x] for x
            in range(len(string_split))]

      start_position = element

    return string_split #list of values

S= "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

['_', '_', '30', '_', '_', '_', '50', '_', '_']
[2, 6, 8]
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
     dict_f_intersect_s = dict()

     for list_of_item in A:
         dict_key = str(list_of_item[0]) + str (list_of_item[1]) #(Concatinating F and S values to make it as key )
         dict_f_intersect_s[dict_key] = 0 # Assigning value to key

    #print(dict_f_intersect_s)({'F1S1': 0, 'F2S2': 0, 'F3S3': 0, 'F1S2': 0, 'F2S3': 0, 'F3S2': 0, 'F2S1': 0, 'F4S1': 0, 'F4S3': 0, 'F5S1': 0})

     dict_s = {'S1': 0, 'S2': 0, 'S3': 0}

     for i in range(len(A)):
        f_intersection_s_key = A[i][0] + A[i][1]  
        dict_f_intersect_s[f_intersection_s_key] += 1 #Increasing the count whenever the certain combination of F and s occurs

        s_key = A[i][1]
        dict_s[s_key] += 1 #Increasing the count whenever the certain  s occurs


        #print(dict_f_intersect_s)
        #print(dict_s)

     #Computing probablities and finding the values
     
     print('a. P(F=F1|S==S1)={F1S1}/{S1}, P(F=F1|S==S2)={F1S2}/{S2}, P(F=F1|S==S3)={F1S3}/{S3}'.format(
                                                                                                          F1S1=dict_f_intersect_s.get(
                                                                                                              'F1S1',
                                                                                                              0), S1=
                                                                                                          dict_s[
                                                                                                              'S1'],
                                                                                                          F1S2=dict_f_intersect_s.get(
                                                                                                              'F1S2',
                                                                                                              0), S2=
                                                                                                          dict_s[
                                                                                                              'S2'],
                                                                                                          F1S3=dict_f_intersect_s.get(
                                                                                                              'F1S3',
                                                                                                              0), S3=
                                                                                                          dict_s[
                                                                                                              'S3']))
     print('b. P(F=F2|S==S1)={F2S1}/{S1}, P(F=F2|S==S2)={F2S2}/{S2}, P(F=F2|S==S3)={F2S3}/{S3}'.format(
                                                                                                          F2S1=dict_f_intersect_s.get(
                                                                                                              'F2S1',
                                                                                                              0), S1=
                                                                                                          dict_s[
                                                                                                              'S1'],
                                                                                                          F2S2=dict_f_intersect_s.get(
                                                                                                              'F2S2',
                                                                                                              0), S2=
                                                                                                          dict_s[
                                                                                                              'S2'],
                                                                                                          F2S3=dict_f_intersect_s.get(
                                                                                                              'F2S3',
                                                                                                              0), S3=
                                                                                                          dict_s[
                                                                                                              'S3']))

     print('c. P(F=F3|S==S1)={F3S1}/{S1}, P(F=F3|S==S2)={F3S2}/{S2}, P(F=F3|S==S3)={F3S3}/{S3}'.format(
                                                                                                          F3S1=dict_f_intersect_s.get(
                                                                                                              'F3S1',
                                                                                                              0), S1=
                                                                                                          dict_s[
                                                                                                              'S1'],
                                                                                                          F3S2=dict_f_intersect_s.get(
                                                                                                              'F3S2',
                                                                                                              0), S2=
                                                                                                          dict_s[
                                                                                                              'S2'],
                                                                                                          F3S3=dict_f_intersect_s.get(
                                                                                                              'F3S3',
                                                                                                              0), S3=
                                                                                                          dict_s[
                                                                                                              'S3']))

     print('d. P(F=F4|S==S1)={F4S1}/{S1}, P(F=F4|S==S2)={F4S2}/{S2}, P(F=F4|S==S3)={F4S3}/{S3}'.format(
                                                                                                          F4S1=dict_f_intersect_s.get(
                                                                                                              'F4S1',
                                                                                                              0), S1=
                                                                                                          dict_s[
                                                                                                              'S1'],
                                                                                                          F4S2=dict_f_intersect_s.get(
                                                                                                              'F4S2',
                                                                                                              0), S2=
                                                                                                          dict_s[
                                                                                                              'S2'],
                                                                                                          F4S3=dict_f_intersect_s.get(
                                                                                                              'F4S3',
                                                                                                              0), S3=
                                                                                                          dict_s[
                                                                                                              'S3']))

     print('e. P(F=F5|S==S1)={F5S1}/{S1}, P(F=F5|S==S2)={F5S2}/{S2}, P(F=F5|S==S3)={F5S3}/{S3}'.format(
                                                                                                          F5S1=dict_f_intersect_s.get(
                                                                                                              'F5S1',
                                                                                                              0), S1=
                                                                                                          dict_s[
                                                                                                              'S1'],
                                                                                                          F5S2=dict_f_intersect_s.get(
                                                                                                              'F5S2',
                                                                                                              0), S2=
                                                                                                          dict_s[
                                                                                                              'S2'],
                                                                                                          F5S3=dict_f_intersect_s.get(
                                                                                                              'F5S3',
                                                                                                              0), S3=
                                                                                                          dict_s[
                                                                                                              'S3']))

    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code

    S1_set_of_words = set(S1.split(" ")) #Spliting the sentence into set of words
    S2_set_of_words = set(S2.split(" "))

    print(S1_set_of_words)
    print(S2_set_of_words)

    common_words= int(len(S1_set_of_words.intersection(S2_set_of_words))), #Calculating the length of common words
    #print(common_words)({'column', 'will', 'only', 'the', 'uniques', 'contain', 'values'})
    S1_not_in_s2 = list(S1_set_of_words - S2_set_of_words) #Words in S1 but not in S2
    S2_not_in_s2 = list(S2_set_of_words - S1_set_of_words) #Words in S2 but not in S1

    a = common_words 
    b = S1_not_in_s2
    c=  S2_not_in_s2 

    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(f"a. Number of common words between S1, S2:{a[0]}")
print(f"b.Words in S1 but not in S2:{b}")
print(f"c.Words in S2 but not in S1:{c}")

{'first', 'will', 'column', 'F', 'values', 'only', 'uniques', '5', 'the', 'contain'}
{'column', 'will', 'values', 'only', '3', 'uniques', 'second', 'the', 'S', 'contain'}
a. Number of common words between S1, S2:7
b.Words in S1 but not in S2:['first', 'F', '5']
c.Words in S2 but not in S1:['3', 'second', 'S']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
from math import log

def compute_log_loss(A):
    # your code
    Total_log_values =0
    for ele in A:
        Total_log_values += (
            ele[0] * log(ele[1], 10) + (
                (1 - ele[0]) * log(1- ele[1], 10)
            )
        )

    loss = -1* Total_log_values /len(A)

    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)



0.42430993457031635
